name: nadz
description: Monads for Dart, but fun and practical
version: 0.0.5-beta
repository: https://github.com/MelbourneDeveloper/nadz

environment:
  sdk: ^3.1.3

dev_dependencies:
  austerity: ^1.2.0
  lints: ^3.0.0
  test: ^1.21.0
